### ISSUE TITLE
[Request] FAB should respond when keyboard is showing

### ISSUE THREAD

**Issue by ltGuillaume** [apozas/contactdiary#33] opened 2021-01-06 03:14 UTC
**Is your feature request related to a problem? Please describe.**
When editing contact / event details, the Floating Action Button (FAB) is nicely positioned above the keyboard, so I always press it after I completed the last input field (with the keyboard still showing). But instead of saving and closing the entry as expected, it merely closes the keyboard. So in effect, you need to press it twice. 

**Describe the solution you'd like**
The FAB should respond with saving&closing the entry, even when the keyboard is showing. This is the expected behavior.

**Comment by apozas** [comment] 2021-01-07 10:36
Hi Guillaume,

Thank you for the feedback. I agree that the expected behavior should be the FAB responding always on click, regardless of the keyboard showing or not. In trying to reproduce the issue you are describing, both in `v1.3.3` and `v1.4.0`, I found what looks like a "warming up" effect (that I don't have an explanation for yet). For instance, here is one of the things I have tried:

New Contact -> Set Name (compulsory) -> Click on Notes but write nothing -> Press FAB -> **The keyboard disappears but the contact is not saved** -> Press FAB -> The contact is saved -> Click the contact in the list -> Click on Notes but write nothing -> Press FAB -> **The keyboard disappears but the contact is not saved** -> Write something in Notes -> Press FAB -> **The contact is saved**

And from then on, the process New Contact -> Set Name (compulsory) -> Click on Notes but write nothing -> Press FAB correctly saves the entries, *even when I force close and reopen the app*. I see similar process with other text fields, like the Phone field.

Do you experience similar phenomena?

**Comment by ltGuillaume** [comment] 2021-01-07 13:32
I cannot reproduce the behavior you're describing: for me it never gets to "Press FAB -> The contact is saved".

**Comment by apozas** [comment] 2021-01-07 15:40
This is so, so strange. I will keep investigating, and come back when I have more information. In the meantime, it would be useful to know of people who experience this, but also of people who do *not*, and know their respective Android versions, phone models, and app versions.

**Comment by ltGuillaume** [comment] 2021-01-07 15:47
I think I found something. If you tap it as fast as possible, it tends to save and close. If you press and hold the FAB for a small amount of time (which is pretty normal), then only the keyboard disappears.

**Comment by apozas** [comment] 2021-01-07 16:08
Well, this I *can* reproduce, and I may have an explanation for it. There is a [constant listener](https://github.com/apozas/contactdiary/blob/master/android_app/app/src/main/java/com/apozas/contactdiary/NewContactActivity.kt#L251) that is intended to close the keyboard when tapping anywhere else in the screen. This includes the FAB. Thus, a press triggers the hiding of the keyboard and the subsequent actual press. If the finger is released too early, the FAB is still where the press is done, so the action of saving is performed. When the finger is released too late, the FAB has already moved and thus no action is taken after hiding the keyboard. This could explain the variances on different phones and the "warming up" effect.

What I'm thinking for fixing this is to collapse the keyboard whenever a touch is done anywhere in the screen except the FAB. After all, if you press the FAB you won't want to navigate around any more. A simple change [here](https://github.com/apozas/contactdiary/blob/master/android_app/app/src/main/java/com/apozas/contactdiary/NewContactActivity.kt#L253) should do the trick. I'll try it as soon as I get to the PC again.

**Comment by ltGuillaume** [comment] 2021-01-07 16:14
Yeah I think adding a check for the FAB would do the trick, great!

**Comment by apozas** [comment] 2021-01-07 18:44
Yes, this seems to do the trick :D

In fixing it, I learnt that possibly the best way of handling this is via the [`performClick`](https://developer.android.com/reference/android/view/View#performClick()) function (I realized this because adding a `performClick` removes a warning I've been getting in the code since the beginning). However, when doing so I am having more problems than solutions: it seems like every time I press the screen I am actioning two clicks, which is giving trouble with the mitigation measures popup. So, for now, I will just remove the FAB from the objects where the listener is activated. I'm proceeding to close the issue, but if when the new version comes out the problem seems to be still there, feel free to reopen it.

**Closed** 2021-01-07 18:45 UTC
